import { VideoProviderError, type NativeVideoJob, type VideoCreateInput, type VideoDownload, type VideoProviderAdapter } from '../types';
function parse(raw:string){try{return raw?JSON.parse(raw):{}}catch{return {raw}}}
function refObj(r:any){return {image:{inlineData:{mimeType:r.mimeType,data:r.dataBase64}},referenceType:'asset'}}
function videoUri(body:any){return body?.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri||body?.response?.generatedVideos?.[0]?.video?.uri||body?.response?.generatedVideos?.[0]?.video?.url}
export const geminiVideoAdapter:VideoProviderAdapter={id:'gemini',envKey:'GEMINI_API_KEY',defaultModel:process.env.SCEN_GEMINI_VIDEO_MODEL||'veo-3.1-generate-preview',isConfigured:()=>Boolean(process.env.GEMINI_API_KEY),
 async test(modelOverride){const key=process.env.GEMINI_API_KEY;if(!key)throw new VideoProviderError('gemini','GEMINI_API_KEY is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_GEMINI_VIDEO_MODEL||'veo-3.1-generate-preview';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}?key=${encodeURIComponent(key)}`);const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('gemini',b?.error?.message||`Gemini model check failed (${r.status})`,r.status,r.status===429||r.status>=500,b?.error?.status);return {ok:true,model,detail:b?.name||model}},
 supports(input){if(input.seconds!==8)return {ok:false,reason:'Veo 3.1 route currently generates 8-second clips'};if(input.references.length>3)return {ok:false,reason:'Veo 3.1 supports up to three reference images'};return {ok:true}},
 async create(input,signal,modelOverride){const key=process.env.GEMINI_API_KEY;if(!key)throw new VideoProviderError('gemini','GEMINI_API_KEY is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_GEMINI_VIDEO_MODEL||'veo-3.1-generate-preview';const cap=this.supports(input,model);if(!cap.ok)throw new VideoProviderError('gemini',cap.reason||'Unsupported capability',422,true,'unsupported_capability');const params:any={aspectRatio:input.aspectRatio,resolution:input.resolution==='4K'?'4k':input.resolution};const instance:any={prompt:input.prompt};if(input.mode==='image'&&input.references[0])instance.image={inlineData:{mimeType:input.references[0].mimeType,data:input.references[0].dataBase64}};if(input.mode==='frames'&&input.references[0]){instance.image={inlineData:{mimeType:input.references[0].mimeType,data:input.references[0].dataBase64}};params.lastFrame={inlineData:{mimeType:input.references[1].mimeType,data:input.references[1].dataBase64}}}else if(input.references.length>1){params.referenceImages=input.references.slice(0,3).map(refObj)}const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:predictLongRunning`,{method:'POST',signal,headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({instances:[instance],parameters:params})});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('gemini',b?.error?.message||`Veo create failed (${r.status})`,r.status,r.status===429||r.status>=500,b?.error?.status);if(!b?.name)throw new VideoProviderError('gemini','Veo returned no operation name',502,true,'empty_job');return {nativeId:b.name,provider:'gemini',model,status:'queued',progress:0,seconds:8,providerRequestId:b.name}},
 async status(nativeId,signal,modelHint){const key=process.env.GEMINI_API_KEY;if(!key)throw new VideoProviderError('gemini','GEMINI_API_KEY is not configured',503,true,'missing_key');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/${nativeId.replace(/^\//,'')}`,{signal,headers:{'x-goog-api-key':key}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('gemini',b?.error?.message||`Veo operation status failed (${r.status})`,r.status,r.status===429||r.status>=500,b?.error?.status);const done=Boolean(b?.done);const failed=Boolean(b?.error);return {nativeId,provider:'gemini',model:modelHint||process.env.SCEN_GEMINI_VIDEO_MODEL||'veo-3.1-generate-preview',status:failed?'failed':done?'completed':'in_progress',progress:done?100:Math.max(5,Number(b?.metadata?.progressPercent||b?.metadata?.progress||25)),seconds:8,detail:b?.error?.message||videoUri(b)||undefined,providerRequestId:nativeId}},
 async download(nativeId,signal){const key=process.env.GEMINI_API_KEY;if(!key)throw new VideoProviderError('gemini','GEMINI_API_KEY is not configured',503,true,'missing_key');const status=await fetch(`https://generativelanguage.googleapis.com/v1beta/${nativeId.replace(/^\//,'')}`,{signal,headers:{'x-goog-api-key':key}});const raw=await status.text(),b=parse(raw);if(!status.ok)throw new VideoProviderError('gemini',b?.error?.message||'Veo status failed',status.status,status.status>=500);const uri=videoUri(b);if(!uri)throw new VideoProviderError('gemini','Veo video is not ready',409,true,'not_ready');const r=await fetch(uri,{signal,headers:{'x-goog-api-key':key}});if(!r.ok)throw new VideoProviderError('gemini',`Veo download failed (${r.status})`,r.status,r.status>=500);return {bytes:new Uint8Array(await r.arrayBuffer()),contentType:r.headers.get('content-type')||'video/mp4',filename:'scen-veo.mp4'}}
};
