import { openAISize } from '../config';
import { VideoProviderError, type NativeVideoJob, type VideoCreateInput, type VideoDownload, type VideoProviderAdapter } from '../types';
function parse(raw:string){try{return raw?JSON.parse(raw):{}}catch{return {raw}}}
function norm(body:any,model:string):NativeVideoJob{const status=body?.status==='completed'?'completed':body?.status==='failed'?'failed':body?.status==='queued'?'queued':'in_progress';return {nativeId:String(body?.id||''),provider:'openai',model:String(body?.model||model),status,progress:Number(body?.progress||0),seconds:Number(body?.seconds||0),detail:body?.error?.message||undefined,providerRequestId:body?.id}}
export const openAIVideoAdapter:VideoProviderAdapter={id:'openai',envKey:'OPENAI_API_KEY',defaultModel:process.env.SCEN_OPENAI_VIDEO_MODEL||'sora-2',isConfigured:()=>Boolean(process.env.OPENAI_API_KEY),
 async test(modelOverride){const key=process.env.OPENAI_API_KEY;if(!key)throw new VideoProviderError('openai','OPENAI_API_KEY is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_OPENAI_VIDEO_MODEL||'sora-2';const r=await fetch(`https://api.openai.com/v1/models/${encodeURIComponent(model)}`,{headers:{Authorization:`Bearer ${key}`}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('openai',b?.error?.message||`OpenAI model check failed (${r.status})`,r.status,r.status===429||r.status>=500,b?.error?.code);return {ok:true,model,detail:b?.id||model}},
 supports(input,modelOverride){const model=modelOverride||process.env.SCEN_OPENAI_VIDEO_MODEL||'sora-2';if(input.mode==='frames')return {ok:false,reason:'first+last-frame mode is not in the OpenAI create-video contract'};if(input.references.length>1)return {ok:false,reason:'OpenAI create video accepts one input reference'};if(!openAISize(input.aspectRatio,input.resolution,model))return {ok:false,reason:'requested resolution is unsupported by this Sora route'};return {ok:true}},
 async create(input,signal,modelOverride){const key=process.env.OPENAI_API_KEY;if(!key)throw new VideoProviderError('openai','OPENAI_API_KEY is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_OPENAI_VIDEO_MODEL||'sora-2';const cap=this.supports(input,model);if(!cap.ok)throw new VideoProviderError('openai',cap.reason||'Unsupported capability',422,true,'unsupported_capability');const size=openAISize(input.aspectRatio,input.resolution,model)!;const payload:any={model,prompt:input.prompt,seconds:String(input.seconds),size};if(input.references[0])payload.input_reference={image_url:`data:${input.references[0].mimeType};base64,${input.references[0].dataBase64}`};const r=await fetch('https://api.openai.com/v1/videos',{method:'POST',signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('openai',b?.error?.message||`OpenAI video create failed (${r.status})`,r.status,r.status===408||r.status===409||r.status===429||r.status>=500,b?.error?.code);const job=norm(b,model);if(!job.nativeId)throw new VideoProviderError('openai','OpenAI returned no video job id',502,true,'empty_job');return job},
 async status(nativeId,signal,modelHint){const key=process.env.OPENAI_API_KEY;if(!key)throw new VideoProviderError('openai','OPENAI_API_KEY is not configured',503,true,'missing_key');const r=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(nativeId)}`,{signal,headers:{Authorization:`Bearer ${key}`}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('openai',b?.error?.message||`OpenAI video status failed (${r.status})`,r.status,r.status===429||r.status>=500,b?.error?.code);return norm(b,modelHint||'sora-2')},
 async download(nativeId,signal):Promise<VideoDownload>{const key=process.env.OPENAI_API_KEY;if(!key)throw new VideoProviderError('openai','OPENAI_API_KEY is not configured',503,true,'missing_key');const r=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(nativeId)}/content`,{signal,headers:{Authorization:`Bearer ${key}`}});if(!r.ok){const raw=await r.text();throw new VideoProviderError('openai',parse(raw)?.error?.message||`OpenAI video download failed (${r.status})`,r.status,r.status>=500)}return {bytes:new Uint8Array(await r.arrayBuffer()),contentType:r.headers.get('content-type')||'video/mp4',filename:`scen-${nativeId}.mp4`}}
};
