import { VideoProviderError, type NativeVideoJob, type VideoCreateInput, type VideoDownload, type VideoProviderAdapter } from '../types';
function parse(raw:string){try{return raw?JSON.parse(raw):{}}catch{return {raw}}}
function splitModel(m:string){const [owner,name]=m.split('/');if(!owner||!name)throw new VideoProviderError('replicate','Replicate model must be owner/name',400,false,'invalid_model');return {owner,name}}
function outputUrl(b:any){if(typeof b?.output==='string')return b.output;if(Array.isArray(b?.output))return b.output.find((x:any)=>typeof x==='string');return b?.output?.url}
function norm(b:any,model:string):NativeVideoJob{const s=b?.status==='succeeded'?'completed':b?.status==='failed'?'failed':b?.status==='canceled'?'canceled':b?.status==='starting'?'queued':'in_progress';return {nativeId:String(b?.id||''),provider:'replicate',model:String(b?.model||model),status:s,progress:s==='completed'?100:s==='queued'?5:50,seconds:Number(b?.metrics?.output_seconds||0),detail:b?.error||outputUrl(b)||undefined,providerRequestId:b?.id}}
export const replicateVideoAdapter:VideoProviderAdapter={id:'replicate',envKey:'REPLICATE_API_TOKEN',defaultModel:process.env.SCEN_REPLICATE_VIDEO_MODEL||'google/veo-3',isConfigured:()=>Boolean(process.env.REPLICATE_API_TOKEN),
 async test(modelOverride){const key=process.env.REPLICATE_API_TOKEN;if(!key)throw new VideoProviderError('replicate','REPLICATE_API_TOKEN is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_REPLICATE_VIDEO_MODEL||'google/veo-3';const {owner,name}=splitModel(model);const r=await fetch(`https://api.replicate.com/v1/models/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`,{headers:{Authorization:`Bearer ${key}`}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('replicate',b?.detail||`Replicate model check failed (${r.status})`,r.status,r.status===429||r.status>=500);return {ok:true,model,detail:b?.name||model}},
 supports(input){if(input.mode==='frames')return {ok:false,reason:'generic Replicate adapter does not assume first/last-frame input names'};return {ok:true}},
 async create(input,signal,modelOverride){const key=process.env.REPLICATE_API_TOKEN;if(!key)throw new VideoProviderError('replicate','REPLICATE_API_TOKEN is not configured',503,true,'missing_key');const model=modelOverride||process.env.SCEN_REPLICATE_VIDEO_MODEL||'google/veo-3';const cap=this.supports(input,model);if(!cap.ok)throw new VideoProviderError('replicate',cap.reason||'Unsupported capability',422,true,'unsupported_capability');const {owner,name}=splitModel(model);const payload:any={prompt:input.prompt,aspect_ratio:input.aspectRatio,duration:input.seconds,resolution:input.resolution.toLowerCase()};if(input.references[0])payload.image=`data:${input.references[0].mimeType};base64,${input.references[0].dataBase64}`;const r=await fetch(`https://api.replicate.com/v1/models/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/predictions`,{method:'POST',signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({input:payload})});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('replicate',b?.detail||`Replicate prediction create failed (${r.status})`,r.status,r.status===429||r.status>=500);const job=norm(b,model);if(!job.nativeId)throw new VideoProviderError('replicate','Replicate returned no prediction id',502,true,'empty_job');return {...job,seconds:input.seconds}},
 async status(nativeId,signal,modelHint){const key=process.env.REPLICATE_API_TOKEN;if(!key)throw new VideoProviderError('replicate','REPLICATE_API_TOKEN is not configured',503,true,'missing_key');const r=await fetch(`https://api.replicate.com/v1/predictions/${encodeURIComponent(nativeId)}`,{signal,headers:{Authorization:`Bearer ${key}`}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('replicate',b?.detail||`Replicate status failed (${r.status})`,r.status,r.status===429||r.status>=500);return norm(b,modelHint||process.env.SCEN_REPLICATE_VIDEO_MODEL||'replicate-video')},
 async cancel(nativeId,signal){const key=process.env.REPLICATE_API_TOKEN;if(!key)throw new VideoProviderError('replicate','REPLICATE_API_TOKEN is not configured',503,true,'missing_key');const r=await fetch(`https://api.replicate.com/v1/predictions/${encodeURIComponent(nativeId)}/cancel`,{method:'POST',signal,headers:{Authorization:`Bearer ${key}`}});const raw=await r.text(),b=parse(raw);if(!r.ok)throw new VideoProviderError('replicate',b?.detail||`Replicate cancel failed (${r.status})`,r.status,r.status>=500);return norm(b,process.env.SCEN_REPLICATE_VIDEO_MODEL||'replicate-video')},
 async download(nativeId,signal):Promise<VideoDownload>{const key=process.env.REPLICATE_API_TOKEN;if(!key)throw new VideoProviderError('replicate','REPLICATE_API_TOKEN is not configured',503,true,'missing_key');const s=await fetch(`https://api.replicate.com/v1/predictions/${encodeURIComponent(nativeId)}`,{signal,headers:{Authorization:`Bearer ${key}`}});const raw=await s.text(),b=parse(raw);if(!s.ok)throw new VideoProviderError('replicate',b?.detail||'Replicate status failed',s.status,s.status>=500);const url=outputUrl(b);if(!url)throw new VideoProviderError('replicate','Replicate output is not ready',409,true,'not_ready');const r=await fetch(url,{signal,headers:{Authorization:`Bearer ${key}`}});if(!r.ok)throw new VideoProviderError('replicate',`Replicate output download failed (${r.status})`,r.status,r.status>=500);return {bytes:new Uint8Array(await r.arrayBuffer()),contentType:r.headers.get('content-type')||'video/mp4',filename:`scen-${nativeId}.mp4`}}
};
