import crypto from 'node:crypto';import type {NextRequest,NextResponse} from 'next/server';import {db} from '../data/db';
export const USER_COOKIE='scen_user_session';
export type UserSession={sub:string;workspaceId:string;role:string;plan?:string;email?:string;emailVerified?:boolean;sid:string;exp:number};
export class UserAuthError extends Error{status=401}
const hash=(raw:string)=>crypto.createHash('sha256').update(raw).digest('hex');
const days=()=>Math.max(1,Math.min(90,Number(process.env.SCEN_AUTH_SESSION_DAYS||30)));
export async function createSession(input:{userId:string;workspaceId:string;userAgent?:string|null;ipHint?:string|null}){const sql=db(),raw=crypto.randomBytes(32).toString('base64url'),sid='ses_'+crypto.randomUUID(),exp=new Date(Date.now()+days()*864e5);await sql`insert into auth_sessions(id,token_hash,user_id,workspace_id,user_agent,ip_hint,expires_at) values(${sid},${hash(raw)},${input.userId},${input.workspaceId},${String(input.userAgent||'').slice(0,300)},${String(input.ipHint||'').slice(0,80)},${exp})`;return {raw,sid,expiresAt:exp}}
export function setSessionCookie(res:NextResponse,raw:string,expiresAt:Date){res.cookies.set(USER_COOKIE,raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',expires:expiresAt})}
export function clearSessionCookie(res:NextResponse){res.cookies.set(USER_COOKIE,'',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:0})}
export async function requireSession(req:NextRequest):Promise<UserSession>{if(process.env.NODE_ENV!=='production'&&process.env.SCEN_AI_ALLOW_DEV_ANON==='true')return{sub:'dev-user',workspaceId:'dev-workspace',role:'owner',plan:'dev',email:'dev@scen.local',emailVerified:true,sid:'dev-session',exp:Math.floor(Date.now()/1000)+3600};const raw=req.cookies.get(USER_COOKIE)?.value;if(!raw)throw new UserAuthError('User session required');const sql=db(),rows=await sql`select s.id,s.user_id,s.workspace_id,s.expires_at,u.email,u.email_verified,m.role,bs.plan_key from auth_sessions s join users u on u.id=s.user_id join memberships m on m.workspace_id=s.workspace_id and m.user_id=s.user_id left join lateral (select plan_key from billing_subscriptions b where b.workspace_id=s.workspace_id and b.status in ('active','authenticated') order by b.updated_at desc limit 1) bs on true where s.token_hash=${hash(raw)} and s.revoked_at is null and s.expires_at>now() limit 1`;const x=rows[0];if(!x)throw new UserAuthError('Session expired or revoked');await sql`update auth_sessions set last_seen_at=now() where id=${x.id} and last_seen_at<now()-interval '5 minutes'`;return{sub:x.user_id,workspaceId:x.workspace_id,role:x.role,plan:x.plan_key||undefined,email:x.email||undefined,emailVerified:!!x.email_verified,sid:x.id,exp:Math.floor(new Date(x.expires_at).getTime()/1000)}}
export async function revokeRaw(raw:string){if(!raw)return;const sql=db();await sql`update auth_sessions set revoked_at=now() where token_hash=${hash(raw)} and revoked_at is null`}
export async function listSessions(s:UserSession){const sql=db();return await sql`select id,user_agent as "deviceLabel",ip_hint as "ipHint",last_seen_at as "lastSeenAt",created_at as "createdAt",expires_at as "expiresAt",(id=${s.sid}) as current from auth_sessions where user_id=${s.sub} and revoked_at is null and expires_at>now() order by last_seen_at desc`}
export async function revokeSession(s:UserSession,id:string){const sql=db();const r=await sql`update auth_sessions set revoked_at=now() where id=${id} and user_id=${s.sub} and id<>${s.sid} and revoked_at is null returning id`;return !!r[0]}
export async function revokeOthers(s:UserSession){const sql=db();const r=await sql`update auth_sessions set revoked_at=now() where user_id=${s.sub} and id<>${s.sid} and revoked_at is null returning id`;return r.length}
export async function revokeAllForUser(userId:string){const sql=db();await sql`update auth_sessions set revoked_at=now() where user_id=${userId} and revoked_at is null`}
